services:
  postgres:
    image: postgres:17-alpine
    container_name: my_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
