services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  httpserver:
    build:
      context: ./httpServer_project
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CONFIG_PATH: /app/config/prod.yaml
      HTTP_USER: ${HTTP_USER}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  pgdata: 
