env: "local" #local, dev, prod

postgres:
  dsn: "host=localhost port=5432 user=postgres password=1230 dbname=northwind_psql sslmode=disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s