env: "local" #local, dev, prod

postgres:
  dsn: "host=localhost port=5433 user=postgres password=1230 dbname=url_shortener sslmode=disable"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s